### ISSUE TITLE
Sensitive Server Side information Disclosure

### ISSUE THREAD

**Issue by sanjogpandasp** [HospitalRun/hospitalrun-dblisteners#6]
Hi,

There is a sensitive information disclosure which reflects DB and system logs.

Try to browse to [https://beta.hospitalrun.io/db/config/_changes](url)

**Comment by jkleinsc** [comment]
@sanjogpandasp thanks for this information.  I am in process on a fix.

**Comment by jkleinsc** [comment]
@sanjogpandasp I have updated the couch initialization scripts to disallow changing the config db, so I am going to close this issue.  Thank you for reporting this.
